### ISSUE TITLE
Try statement failed

### ISSUE THREAD

**Issue by XavierBeheydt** [bentasker/Wake-On-Lan-Python#6] opened 2019-09-13 15:26 UTC
Hello, sorry for my language, English is my bad.

So when, I try to use your script. I Have usage fonction calling every time ???
I think what the Try statement not run normaly.

My config INI have just one mac address.

**Comment by jNullj** [comment] 2021-08-21 10:01
Could you add the error that's shows up and the way you attempt to run the script?

**Comment by DiGiSoUL84** [comment] 2023-01-21 21:26
I'm getting this error

File "wol.py", line 41
    def __init__(self, *extra_search_paths, prefer_local_config=False, **config):
                                                              ^
SyntaxError: invalid syntax

**Comment by jNullj** [comment] 2023-01-21 22:46
if it is not related to the original issue i think it would be better to state that in another issue, also what version of python are you using? you can find out using `python --version`

**Comment by DiGiSoUL84** [comment] 2023-01-21 23:20
@jNullj my apologies I will create a new issue

**Comment by bentasker** [comment] 2023-01-22 10:26
@DiGiSoUL84 as @jNullj alluded to, this is almost certainly because you're trying to run with Python 2.

If I spin out a Python2 container, I get an error on the same line
```
root@3b659e8ae77d:/# python2 /src/wol.py 
  File "/src/wol.py", line 41
    def __init__(self, *extra_search_paths, prefer_local_config=False, **config):
                                                              ^
SyntaxError: invalid syntax
```
This isn't something that we're going to fix: Python 2 is well past EOL, security support for 2.7.18 ended in 2020.

If you're currently unable to use a newer version of Python, there are two options available to you

Use the last version of the script to support Py2 (from 2014!), available [here](https://github.com/bentasker/Wake-On-Lan-Python/blob/2131b8daa310e25a74ad1ff40632a97847aa44e9/wol.py) (the config file format should be the same)

Run the utility in docker, I've just merged a change to add a Dockerfile - assuming the system you're on has Docker you should be able to do this to auto-generate the config file

```
docker run \
--rm \
-v ~/.config/bentasker.Wake-On-Lan-Python/:/wol_config \
bentasker12/wake-on-lan-python list
```

You'll need to correct the broadcast address that it calculates, so do
```
ip a
```
do get your current IP (e.g. `192.168.1.5`) and make a note of the first 3 octets.

Then edit `~/.config/bentasker.Wake-On-Lan-Python/` and update the `General` section to use your noted prefix
```
[General]
broadcast = 192.168.1.255
```

Once you've set mac addresses etc in the config, you should be able to run
```
docker run \
--rm \
-v ~/.config/bentasker.Wake-On-Lan-Python/:/wol_config \
bentasker12/wake-on-lan-python MyPC
```

Although, personally I'd add an alias for it:
```
echo alias wol="docker run --rm -v ~/.config/bentasker.Wake-On-Lan-Python/:/wol_config bentasker12/wake-on-lan-python " | tee -a ~/.bashrc
```

Start a new terminal and you should simply be able to do
```
wol myPC
```

All that being said - it *really* would be a good idea to get onto a version of Python that's still getting security updates.

**Comment by bentasker** [comment] 2023-01-22 10:29
It doesn't look like there's anything to do here - the original reporter never replied (I can't seem to reproduce any behaviour similar to that being described).

Closing ticket

**Closed as completed by bentasker** 2023-01-22 10:29 UTC
Labels: invalid

**Comment by DiGiSoUL84** [comment] 2023-01-22 13:57
@bentasker I did find that I was in Python 2 and when I went to 3.11 I no longer got that error. Wish I would have seen your reply earlier because I got a different error. I'm now getting invalid hostname configured.

**Comment by bentasker** [comment] 2023-01-22 14:01
@DiGiSoUL84 is the error message perhaps "Invalid Hostname Specified"?  There isn't one about an invalid hostname being configured

Can you provide the exact command you've run? Does the hostname you're providing perhaps have spaces in it?

**Comment by DiGiSoUL84** [comment] 2023-01-22 14:13
I cloned the repo,  edited wol_config.ini.example with my broadcast IP & a host machine then renamed to wol_cofig.ini, I made an alias named 'python' for Python3.11 & hostname 'thinkpad', finally ran the following:
~$: python wol.py thinkpad

That's when I get the invalid hostname error. If I run:
~$: python wol.py list

I get the following output:
~$: Configured hostnames:
~$: thinkpad

So it looks like I have it configured right but get error

**Comment by bentasker** [comment] 2023-01-22 14:22
What you're doing should work - if I do the same:
```
$ python ./wol.py thinkpad
Magic packet should be winging its way to: thinkpad
```

The error message might be misleading though, because it gets returned if `wake_on_lan()` does not return true.

Looking at the function definition, the only way that it can return `False` rather than working or throwing an exception is if the config file doesn't have a `mac` line for the hostname

The config should look like this
```
ben@optimus:~/Documents/src.old/Wake-On-Lan-Python$ cat wol_config.ini
# Save this file as .wol_config.ini in the same directory as wol.py

[General]
broadcast=192.168.1.255

[thinkpad]
mac=00:2a:a0:cf:83:15
```

If there's no `mac` line, you'll get the error you're experiencing (the message should probably be clarified).

If you want a quick/easy way to grab the mac address of a remote host, do
```
ping -c 3 [hostname or ip]
arp | grep ip
```

There's an example of mapping out an entire subnet and generating the config [here](https://www.bentasker.co.uk/posts/documentation/linux/258-usurping-the-bthomehub-with-a-raspberry-pi-part-three-routing-remote-administration-and-utilities.html#WakeOnLan)

**Comment by DiGiSoUL84** [comment] 2023-01-22 14:40
I know how arp and all that work do this type of work for living. My config looks exactly like that

**Comment by bentasker** [comment] 2023-01-22 14:43
OK, I've just pushed a branch which should clarify the error being experienced a bit further, so try this

```
curl https://raw.githubusercontent.com/bentasker/Wake-On-Lan-Python/error_clarification/wol.py -o wol_2.py
chmod +x wol_2.py
```

Then run your command again using `wol_2.py` and provide the full commandline and output please

**Comment by DiGiSoUL84** [comment] 2023-01-22 16:20
> OK, I've just pushed a branch which should clarify the error being experienced a bit further, so try this
> 
> ```
> curl https://raw.githubusercontent.com/bentasker/Wake-On-Lan-Python/error_clarification/wol.py -o wol_2.py
> chmod +x wol_2.py
> ```
> 
> Then run your command again using `wol_2.py` and provide the full commandline and output please

Awesome will try this shortly and post the output

**Comment by DiGiSoUL84** [comment] 2023-01-22 16:45
@bentasker 
Just tried the new branch and was successful! Thank you for responding and taking the time to help me out with this! Now just have to take this script and add it to a button card so that I can turn on my laptop from my Home Assistant dashboard!! Again thank you for your help and your time!!

**Comment by bentasker** [comment] 2023-01-22 19:23
> add it to a button card so that I can turn on my laptop from my Home Assistant dashboard!

Nice :) 

No dramas, glad it's working for you (I'm going to merge that branch into master shortly)
